#!/bin/sh
# Sets up the iterm2 plist

APPCONFIGDIRREL=$(dirname $0)
cd $APPCONFIGDIRREL
APPCONFIGDIR=$(pwd -P)

CONFIG=$(echo "'$(cat $APPCONFIGDIR/com.googlecode.iterm2.plist)'")

defaults write com.googlecode.iterm2 $CONFIG
