# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

minApprovals:
  COLLABORATOR: 0
maxRequestedChanges:
  NONE: 0

blockingLabels: 
- hold
blockingTitleRegex: '\bWIP\b'

reportStatus: true
updateBranch: true
deleteBranchAfterMerge: true
