tap 'homebrew/cask-drivers'
tap 'homebrew/cask-versions'
tap 'github/bootstrap'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'homebrew/test-bot'
tap 'mikesplain/versions'

cask 'xquartz'

brew 'ack'
brew 'ag'
brew 'gdbm'
brew 'xz'
brew 'python3'
brew 'asciinema'
brew 'autoconf'
brew 'automake'
brew 'awscli'
brew 'boost'
brew 'git'
brew 'bazelbuild/tap/bazelisk'
brew 'glide'
brew 'isl'
brew 'cloog'
brew 'cmake'
brew 'cscope'
brew 'curl'
brew 'libgpg-error'
brew 'libassuan'
brew 'libgcrypt'
brew 'libksba'
brew 'pth'
brew 'libyaml'
brew 'ec2-api-tools'
brew 'findutils'
brew 'libpng'
brew 'freetype'
brew 'fontconfig'
brew 'gmp'
brew 'mpfr'
brew 'moreutils'
brew 'libmpc'
brew 'jpeg'
brew 'gd'
brew 'gettext'
brew 'git-crypt'
brew 'git-lfs'
brew 'gnu-tar'
brew 'libusb'
brew 'pinentry'
brew 'gnupg'
brew 'govendor'
brew 'gpg'
brew 'libtool'
brew 'graphviz'
brew 'grc'
brew 'heroku/brew/heroku'
brew 'lua'
brew 'highlight'
# brew 'htop'
brew 'httperf'
brew 'hub'
brew 'iftop'
brew 'ipcalc'
brew 'iperf'
brew 'oniguruma'
brew 'jq'
brew 'node'
brew 'jsonlint'
brew 'kubernetes-cli'
brew 'kops'
brew 'kubectx'
brew 'kube-ps1'
brew 'python'
# brew 'mercurial'
brew 'kubernetes-helm'
brew 'libevent'
brew 'libssh'
brew 'libusb-compat'
brew 'neovim'
# brew 'macvim'
brew 'makedepend'
brew 'mas'
brew 'dep'
brew 'maven'
brew 'md5sha1sum'
brew 'msgpack'
brew 'ncdu'
brew 'pcre'
#brew 'nginx', restart_service: true
brew 'nmap'
brew 'node-build'
brew 'nodenv'
brew 'ossp-uuid'
brew 'packer'
brew 'perl'
brew 'postgresql'
brew 'rainbarf'
brew 'ruby-build'
brew 'rbenv'
brew 'rbenv-default-gems'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'ruby'
brew 's3cmd'
brew 'shellcheck'
brew 'slackcat'
brew 'socat'
brew 'ssh-copy-id'
brew 'stern'
brew 'telnet'
brew 'terraform'
brew 'thefuck'
brew 'tmate'
brew 'tmux'
brew 'tree'
brew 'utf8proc'
brew 'vegeta'
brew 'vim'
brew 'wakeonlan'
brew 'watch'
brew 'wget'
brew 'zsh'
brew 'kubernetes-cli'
brew 'libdvdcss'
brew 'jesseduffield/lazygit/lazygit'

cask '1password'
cask 'alfred'
cask 'atom'
cask 'caffeine'
cask 'cakebrew'
cask 'charles'
cask 'cyberduck'
cask 'deepvacuum'
cask 'disk-inventory-x'
cask 'docker'
cask 'dropbox'
cask 'etcher'
cask 'evernote'
cask 'firefox'
cask 'flux'
cask 'github'
cask 'google-cloud-sdk'

cask 'google-chrome'
cask 'google-drive-file-stream'
cask 'gpg-suite'
cask 'intellij-idea-ce'
cask 'iterm2'
cask 'kaleidoscope'
cask 'keepingyouawake'
cask 'keybase'
# cask 'launchrocket'
cask 'libreoffice'
cask 'logitech-options'
# cask 'microsoft-office'
cask 'minikube'
cask 'ngrok'
cask 'openoffice'
cask 'private-internet-access'
cask 'psequel'
cask 'sequel-pro'
cask 'signal'
cask 'skype'
cask 'slack'
cask 'sonos'
cask 'sourcetree'
cask 'spectacle'
cask 'spotify'
cask 'superduper'
cask 'textual'
cask 'thunderbird'
cask 'tigervnc-viewer'
cask 'tor-browser'
cask 'transmission'
cask 'transmit'
cask 'tunnelblick'
cask 'unetbootin'
cask 'vagrant'
cask 'vagrant-manager'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'vlc'
cask 'yujitach-menumeters'
cask 'zoomus'
cask 'zterm'

mas 'Deliveries', id: 924726344
mas 'iMovie', id: 408981434
mas 'Keynote', id: 409183694
# mas 'Microsoft Remote Desktop', id: 715768417
mas 'Monosnap', id: 540348655
mas 'Notability', id: 736189492
mas 'Numbers', id: 409203825
mas 'Pages', id: 409201541
# mas 'Remote Desktop', id: 409907375
mas 'The Unarchiver', id: 425424353
mas 'Things3', id: 904280696
mas 'Tweetbot', id: 557168941
mas 'Wallcat', id: 1000397973
# mas 'Xcode', id: 497799835
