{
  inputs,
  pkgs,
  lib,
  ...
}:
let
  # includeIf matches stored remote URLs before insteadOf rewrites them. Cover
  # conventional URLs as well as explicit account aliases and older checkouts.
  githubIncludes =
    path: organizations: aliases:
    map
      (pattern: {
        condition = "hasconfig:remote.*.url:${pattern}";
        inherit path;
      })
      (
        lib.concatMap (
          organization:
          map (prefix: "${prefix}${organization}/**") [
            "https://github.com/"
            "git@github.com:"
            "ssh://git@github.com/"
          ]
        ) organizations
        ++ lib.concatMap (alias: [
          "${alias}:*/**"
          "git@${alias}:*/**"
          "ssh://git@${alias}/**"
        ]) aliases
      );
in
{
  programs.git = {
    enable = true;
    lfs.enable = true;
    # Allow conditional include files to choose the signing format explicitly.
    signing.format = null;

    settings = {
      user = {
        name = "Mike Splain";
        email = "mike.splain@gmail.com";
      };

      alias = {
        # Print the name of the current upstream tracking branch.
        upstream = "!git config --get branch.$(git current-branch).remote || echo origin";
        # Cherry-pick a commit with your signature.
        sign = "cherry-pick --signoff";
        # Create a pull request on GitHub using the `gh` command.
        pull-request = "!gh pr create -w";
        # Push the current branch upstream to origin using the same branch
        # name for the remote branch.
        upstream-current-branch = "!git push --set-upstream origin $(git current-branch)";
        # Upstream the current branch to origin and create a pull request
        # on GitHub.
        upstream-and-pull-request = "!git upstream-current-branch && git pull-request";
        # Push the current branch and set it as the default upstream branch.
        push-and-set-upstream = "push --set-upstream";
        # Show the commit log with a prettier, clearer history.
        pretty-one-line-log = "log --graph --oneline --decorate";
        # Checkout the main branch and update it.
        pull-main = "!git checkout main && git pull";
        # Shortcut to above
        main = "!git pull-main";
        # Checkout the master branch and update it.
        pull-master = "!git checkout master && git pull";
        # Shortcut to above
        master = "!git pull-master";
        # Checkout the develop branch and update it.
        pull-develop = "!git checkout develop && git pull";
        # Shortcut to above
        develop = "!git pull-develop";
        # Create a new branch by checking out another branch.
        checkout-as-new-branch = "checkout -b";
        # Print the name of the current branch.
        current-branch = "symbolic-ref --short HEAD";

        ## Shortened 'New' Commands
        work-in-progress = "commit -a -m 'WIP'";
        wip = "!git work-in-progress";
        pr = "!git upstream-and-pull-request";
        up = "!git upstream-current-branch";
        l = "!git pretty-one-line-log || true";
        b = "!git checkout-as-new-branch";

        ## Shortened Existing Commands
        p = "pull";
        s = "status --short --branch";
      };

      github.user = ("mike.splain@gmail.com");
      gist.browse = true;
      push = {
        default = "simple";
        autoSetupRemote = true;
      };
      fetch.prune = "1";
      rerere.enabled = true;
      core = {
        mergeoptions = "--no-edit";
        editor = "nvim";
        pager = "hunk pager";
      };
      pager = {
        blame = "hunk pager";
        diff = "hunk pager";
        log = "hunk pager";
        show = "hunk pager";
      };
      help.autocorrect = 1;
      diff.colorMoved = "default";
      merge.conflictstyle = "diff3";
      # mergetool = {
      #   prompt = false;
      #   keepBackup = false;
      #   keepTemporaries = false;
      # };
      apply.whitespace = "fix";
      rebase = {
        autosquash = true;
        autoStash = true;
      };
      hub.protocol = "https";
      # Keep conventional URLs in repositories. Longer organization prefixes take
      # precedence over the personal fallback; each host selects its key through
      # the SSH config generated by 1Password Bookmarks.
      url = {
        "git@github-personal:".insteadOf = [
          "https://github.com/"
          "git@github.com:"
          "ssh://git@github.com/"
          "personalgit:"
          "git@personalgit:"
          "ssh://git@personalgit/"
        ];
        "git@github-work:cisco-sbg/".insteadOf = [
          "https://github.com/cisco-sbg/"
          "git@github.com:cisco-sbg/"
          "ssh://git@github.com/cisco-sbg/"
        ];
        "git@github-work:RobustIntelligence/".insteadOf = [
          "https://github.com/RobustIntelligence/"
          "git@github.com:RobustIntelligence/"
          "ssh://git@github.com/RobustIntelligence/"
        ];
        "git@github-managed:cisco-aispg/".insteadOf = [
          "https://github.com/cisco-aispg/"
          "git@github.com:cisco-aispg/"
          "ssh://git@github.com/cisco-aispg/"
        ];
        # Support older checkouts while their stored URLs are migrated.
        "git@github-work:".insteadOf = [
          "workgit:"
          "git@workgit:"
          "ssh://git@workgit/"
        ];
        "git@github-managed:".insteadOf = [
          "workgit_managed:"
          "git@workgit_managed:"
          "ssh://git@workgit_managed/"
        ];
      };
      commit.verbose = true;
      pull.rebase = true;

      color = {
        ui = true;
        "diff-highlight" = {
          oldNormal = "red bold";
          oldHighlight = "red bold 52";
          newNormal = "green bold";
          newHighlight = "green bold 22";
        };

        diff = {
          meta = "11";
          frag = "magenta bold";
          func = "146 bold";
          commit = "yellow bold";
          old = "red bold";
          new = "green bold";
          whitespace = "red reverse";
        };
      };
    };

    ignores = [
      "*.rej"
      "*.swp"
      "*~"
      ".DS_Store"
    ];

    includes = [
      {
        path = "~/.additional_gitconfig";
      }
      {
        condition = "gitdir:~/.local/share/chezmoi";
        path = "~/.personal_gitconfig";
      }
    ]
    ++
      githubIncludes "~/.personal_gitconfig"
        [
          "mikesplain"
          "kubernetes"
          "homebrew"
        ]
        [ "github-personal" "personalgit" ]
    ++
      githubIncludes "~/.work_gitconfig"
        [
          "RobustIntelligence"
          "cisco-sbg"
        ]
        [ "github-work" "workgit" ]
    ++
      githubIncludes "~/.work_gitconfig_managed"
        [ "cisco-aispg" ]
        [
          "github-managed"
          "workgit_managed"
        ];
  };

  xdg.configFile."hunk/config.toml".text = ''
    theme = "graphite"
    mode = "auto"
    exclude_untracked = false
    line_numbers = true
    wrap_lines = false
  '';

  # gitui is now installed via Homebrew (see darwin/homebrew.nix)
}
