#!/bin/bash
# Install additional things

sh <(curl https://j.mp/spf13-vim3 -L)

# Setup Menumeters

defaults write com.ragingmenace.MenuMeters \
  CPUAverageMultiProcs \
  -int 1
  
defaults write com.ragingmenace.MenuMeters \
  CPUDisplayMode \
  -int 2

defaults write com.ragingmenace.MenuMeters \
  MemDisplayMode \
  -int 4
  
defaults write com.ragingmenace.MenuMeters \
  NetDisplayMode \
  -int 2
  
defaults write com.ragingmenace.MenuMeters \
  com.ragingmenace.MenuMeterDisk \
  -int 0
