#!/bin/sh
# Sets up powerline

# APPCONFIGDIRREL=$(dirname $0)
# cd $APPCONFIGDIRREL
# APPCONFIGDIR=$(pwd -P)


# pip install --user powerline-status psutil bzr pyuv

# git clone https://github.com/powerline/fonts $TMPDIR/powerline
# "$TMPDIR/powerline/install.sh"

# rm -rf $TMPDIR/powerline

# POWERLINECONFIGDIR="$HOME/.config/powerline"

# mkdir -p "$POWERLINECONFIGDIR"
# ln -sfv  "$APPCONFIGDIR/config.json" "$POWERLINECONFIGDIR/config.json"
