#!/bin/sh
# Install app configs

APPCONFIGDIR=$(dirname $0)
SPECTACLECONFIGDIR="~/Library/Application Support/Spectacle"

mkdir -p $SPECTACLECONFIGDIR
ln -sfv  $APPCONFIGDIR/Shortcuts.json $SPECTACLECONFIGDIR/Shortcuts.json
