#!/bin/sh
# Install app configs

APPCONFIGDIRREL=$(dirname $0)
cd $APPCONFIGDIRREL
APPCONFIGDIR=$(pwd -P)

SPECTACLECONFIGDIR="$HOME/Library/Application Support/Spectacle"

mkdir -p "$SPECTACLECONFIGDIR"
ln -sfv  "$APPCONFIGDIR/Shortcuts.json" "$SPECTACLECONFIGDIR/Shortcuts.json"
