name: ops
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
  issue_comment:
    types: [created]

jobs:
  prow:
    runs-on: ubuntu-latest
    steps:
      - uses: jpmcb/prow-github-actions@v1
        with:
          prow-commands: '/assign
            /unassign
            /approve
            /retitle
            /area
            /kind
            /priority
            /remove
            /lgtm
            /close
            /reopen
            /lock
            /milestone
            /hold
            /cc
            /uncc'
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  label-checks:
    runs-on: ubuntu-latest
    needs: prow
    steps:
    - uses: mheap/github-action-required-labels@v1
      with:
        mode: exactly
        count: 0
        labels: "do-not-merge/hold"
    - uses: mheap/github-action-required-labels@v1
      if: github.actor == 'mikesplain'
      with:
        mode: exactly
        count: 1
        labels: "lgtm"

  auto-merge:
    runs-on: ubuntu-latest
    needs: [label-checks, prow]
    # Specifically check that dependabot (or another trusted party) created this pull-request, and that it has been labelled correctly.
    # if: github.event.pull_request.user.login == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dependencies')
    steps:
    - name: Get token
      id: get_token
      uses: mikesplain/actions-app-token@master
      with:
        APP_PEM: ${{ secrets.MERGEBOT_PEM }}
        APP_ID: ${{ secrets.MERGEBOT_ID }}

    - uses: alexwilson/enable-github-automerge-action@main
      with:
        github-token: '${{ steps.get_token.outputs.app_token }}'

    - uses: hmarr/auto-approve-action@v2
      if: github.actor == 'mikesplain'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
