name: GitHub Actions CI
on:
  push:
    branches: master
  pull_request:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 12 * * *'
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - name: Set up Git repository
      uses: actions/checkout@master

    - name: Validate syntax
      run: bash -n *.sh

    - name: Test script/setup
      run: bash script/setup

    - name: Test bashrc
      run: bash -c "source ~/.bashrc"

    - name: Test zshrc
      run: zsh -c "source ~/.zshrc"
      if: matrix.os == 'macOS-latest'

    - name: Brewfile
      run: bash script/test-install.sh
      if: matrix.os == 'macOS-latest'
