name: Tests
on:
  push:
    branches: main
  pull_request:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 12 * * *'
  workflow_dispatch: {}
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # https://github.com/actions/virtual-environments
        os: [ubuntu-latest, macos-12, macos-11, macos-10.15]
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Test Install Chezmoi
      run: ./install.sh

    - name: Test bashrc
      run: bash -c "source ~/.bashrc"

    - name: Test zshrc
      run: zsh -vc "source ~/.zshrc"

    - name: Test diff-so-fancy
      run: zsh -vc "diff-so-fancy"

  notifications:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: Slack Notice Action
      uses: sonots/slack-notice-action@v3.1.2
      with:
        status: ${{ job.status }}
        icon_emoji: ':octocat:'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required, but GitHub should automatically supply
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.
