name: Tests
on:
  push:
  pull_request:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 12 * * *'
  workflow_dispatch: {}
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # https://github.com/actions/virtual-environments
        os:
        # - ubuntu-22.04
        # - ubuntu-20.04
        - macos-12
        # - macos-13
        - macos-14
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4

    - name: Test Install Chezmoi
      run: | 
        hostname
        scutil --get LocalHostName
        sudo hostname testerrrrr
        echo hostname run!
        scutil --set LocalHostName testerrrrr
        hostname
        scutil --get LocalHostName
        


